/**
 * <summary>
 *	Timer for SetPlayerPosFindZ.
 * </summary>
 *
 * <param name="playerID">
 *	The ID of the player
 * </param>
 *
 * <param name="posX">
 *	The X position
 * </param>
 *
 * <param name="posY">
 *	The Y position
 * </param>
 *
 * <param name="posZ">
 *	The Z position
 * </param>
 */

Timer:SetPlayerPosFindZ(playerID, Float:posX, Float:posY, Float:posZ)
{
	SetPlayerPosFindZ(playerID, posX, posY, posZ);
}