// Available sound IDs (Played randomly in register progress)
new musicSoundIDs[] =
{
	1062,
	1068,
	1076,
	1097,
	1183,
	1185,
	1187
};

// Available radio stations (Used in vehicles)
new radioStations[][enum_radioStation] =
{
	{"", ""},// 0 should be "Radio off"
	{"Tortoise 107.9", "http://selfcoders.com:8000/listen.pls?sid=1"},
	{"Super Natural 98.3", "http://selfcoders.com:8000/listen.pls?sid=2"},
	{"Rise FM", "http://selfcoders.com:8000/listen.pls?sid=11"},
	{"Techno4ever", "http://node03.t4e.dj:7000/listen.pls"},
	{"Technobase.fm", "http://listen.technobase.fm/dsl.pls"},
	{"Blackbeats.FM", "http://stream.blackbeatslive.de/;stream.nsv&type=mp3"},
	{"HyperSheep FM", "http://selfcoders.com:8000/listen.pls?sid=3"},
	{"Hot 108 Jamz", "http://scfire-mtc-aa05.stream.aol.com:80/stream/1071"}
};

// Removed standard objects (GTA San Andreas objects)
new removedStandardObjects[][enum_stdObj] =
{
	{985, 2497.41, 2777.07, 11.5312, 1.0},
	{986, 2497.41, 2769.11, 11.5312, 1.0},
	{7172, 2546.03, 2828.73, 11.5391, 1.0},
	{960, 2580.0, 2830.0, 10.0, 70.0},
	{961, 2580.0, 2830.0, 10.0, 70.0},
	{16094, 191.141, 1870.04, 21.4766, 1.0}
};

// Skins
new maleSkins[] =
{
	2,
	6,
	7,
	21,
	98
};
new femaleSkins[] =
{
	131,
	150,
	169,
	190,
	193
};