// Admin levels
#define ADMINLEVEL_SERVERADMIN		1338


// Colors
#define COLOR_ERROR					0xA00000AA
#define COLOR_ME					0x00FF40AA
//#define COLOR_PM					0x804000AA
#define COLOR_SYSTEM				0xC0C0C0AA
#define COLOR_CHAT					0xFFFFFFAA
#define COLOR_CHATOWN				0xAAAAAAAA
#define COLOR_IRC					0x33AA33AA
#define COLOR_INFO					0xFF8C55FF
#define COLOR_USAGE					0x008000AA
#define COLOR_JOINLEAVE				0x74E80099
#define COLOR_NPCCOMMAND			0x00000000


// Help configuration
#define HELP_COMMANDSPERLINE		5


// IRC credentials
#define IRC_HOST					"127.0.0.1"
#define IRC_PORT					6667
#define IRC_SSL						false
#define IRC_USERNAME				"grgserver"
#define IRC_CHANNEL					"#grgserver"


// MySQL credentials
#define MYSQL_HOST					"srv1.selfcoders.com"
#define MYSQL_USERNAME				"grgserver"
#define MYSQL_PASSWORD				"2RuvHtYb7KRh6PVt"
#define MYSQL_DATABASE				"grgserver"


// Register values
#define REGISTER_MINPASSWORD		3
#define REGISTER_MAXPASSWORD		20
#define REGISTER_LEVEL				1
#define REGISTER_ADMINLEVEL			0


// Spawn properties
#define SPAWN_POSX					1958.3783
#define SPAWN_POSY					1343.1572
#define SPAWN_POSZ					15.3746
#define SPAWN_ANGLE					269.1425


// Timers
#define TIMER_FAST					250
#define TIMER_SLOW					5000


// Vehicle configuration
#define VEHICLE_MINHEALTH			30