// IRC credentials
#define IRC_HOST				"srv1.selfcoders.com"
#define IRC_PORT				6667
#define IRC_SSL					false
#define IRC_USERNAME			"samp-server"
#define IRC_PASSWORD			"R8I09ym2ZzeHp4tcPVMj"
#define IRC_CHANNEL				"grgserver"


// MySQL credentials
#define MYSQL_HOST				"localhost"
#define MYSQL_USERNAME			"grgserver"
#define MYSQL_PASSWORD			"2RuvHtYb7KRh6PVt"
#define MYSQL_DATABASE			"grgserver"


// Register values
#define REGISTER_MINPASSWORD	3
#define REGISTER_MAXPASSWORD	20
#define REGISTER_LEVEL			1
#define REGISTER_ADMINLEVEL		0