// Colors
//#define COLOR_ERROR						0xA00000AA
//#define COLOR_ME						0x00FF40AA
//#define COLOR_PM						0x804000AA
//#define COLOR_SYSTEM					0xC0C0C0AA
//#define COLOR_CHAT						0xFFFFFFAA
//#define COLOR_CHATOWN					0xAAAAAAAA
//#define COLOR_LIST_HEADER				0xFF8000AA
//#define COLOR_LIST_ITEM					0x33AA33AA
//#define COLOR_IRC						0xA000FFAA
#define COLOR_INFO						0xFF8C55FF
//#define COLOR_USAGE						0x008000AA
//#define COLOR_NICKNAME					0x2986CEFF
//#define COLOR_JOINLEAVE					0x74E80099
//#define COLOR_WARN						0xBE615099
//#define COLOR_ADMIN						0xFF4000FF
//#define COLOR_AFK						0x0000CCAA
//#define COLOR_USERUNKNOWN				0xFFFF00AA
//#define COLOR_USER						0x33AA33AA
//#define COLOR_3DLABEL_PICKUP			0xFF8000AA


// Command returns
#define COMMAND_UNKNOWN_ERROR			0
#define COMMAND_OK						1


// Dialogs
#define DIALOG_LOGIN					1
#define DIALOG_REGISTER					2


// Spawn properties
#define SPAWN_POSX						1958.3783
#define SPAWN_POSY						1343.1572
#define SPAWN_POSZ						15.3746
#define SPAWN_ANGLE						269.1425